# Generated by Django 3.2.7 on 2022-07-27 08:20

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicescondition',
            name='facility_nursing',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True, verbose_name='5.\tDoes your organization provide Nursing Room/Lactation Station facilities?'),
        ),
        migrations.AlterField(
            model_name='practicescondition',
            name='facility_nursing_others',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Please specify:'),
        ),
        migrations.AlterField(
            model_name='practicescondition',
            name='facility_nursing_utilized',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True, verbose_name='5.1. Have you ever utilized the facility?'),
        ),
        migrations.AlterField(
            model_name='practicescondition',
            name='facility_nursing_utilized_no_reason',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('I don’t need the facility', 'I don’t need the facility'), ('No time to use', 'No time to use'), ('Facility is sub-standard', 'Facility is sub-standard'), ('Others', 'Others')], max_length=500, null=True, verbose_name='5.3.Reason of not utilizing the facility:'),
        ),
        migrations.AlterField(
            model_name='practicescondition',
            name='facility_nursing_utilized_satisfied',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True, verbose_name='5.2. If YES, are you satisfied?'),
        ),
        migrations.AlterField(
            model_name='practicescondition',
            name='facility_nursing_utilized_satisfied_no_reason',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='5.2.2. No, Kindly state your reasons'),
        ),
        migrations.AlterField(
            model_name='practicescondition',
            name='facility_nursing_utilized_satisfied_yes_reason',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='5.2.1. Yes, Kindly state your reasons'),
        ),
        migrations.AlterField(
            model_name='practicescondition',
            name='other_facility',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='10.\tOther available facility for employee:'),
        ),
        migrations.AlterField(
            model_name='practicescondition',
            name='other_reason_absent_family',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Others'),
        ),
        migrations.AlterField(
            model_name='practicescondition',
            name='other_reason_absent_health',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Others'),
        ),
        migrations.AlterField(
            model_name='practicescondition',
            name='other_reason_absent_office',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Others'),
        ),
        migrations.AlterField(
            model_name='practicescondition',
            name='other_reason_tardines_family',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Others'),
        ),
        migrations.AlterField(
            model_name='practicescondition',
            name='other_reason_tardines_health',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Others'),
        ),
        migrations.AlterField(
            model_name='practicescondition',
            name='other_reason_tardines_office',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Others'),
        ),
        migrations.AlterField(
            model_name='practicescondition',
            name='other_reason_undertime_family',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Others'),
        ),
        migrations.AlterField(
            model_name='practicescondition',
            name='other_reason_undertime_health',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Others'),
        ),
        migrations.AlterField(
            model_name='practicescondition',
            name='other_reason_undertime_office',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Others)'),
        ),
    ]
